### ISSUE TITLE
[ Bug ] Live Events Don't Sync ):

### ISSUE THREAD

**Issue by Jadiac5** [RCVolus/league-observer-tool#150]
**Describe the bug**
Live Events stays at yellow and doesn't sync. This makes the Scoreboard Overlay and Popups like Dragons etc. not work / show up.

**To Reproduce**

1. Download & Install "League Observer Tool"
2. Download & Install "League Prod Toolkit"
     -> Join Live Game / From direct or Lobby: Stays at Yellow ):

**Expected behavior**
The "Live Events" Module / Feature in the "League Observer Tool" should sync and update the Scoreboard, also it should trigger the "Live Events"

**Screenshots**
![image](https://github.com/RCVolus/league-observer-tool/assets/114788069/0b0e64f9-e854-4fc8-8f99-09c9d77be3ad)
(FYI: The green squares are the team logos I added as a test, also made the BG for the BO-X score see through)

**System:**

- OS: Windows 11 Pro
- Node: v20.12.0 (Got this via: "node --version" after opening terminal through Windows Button on Keyboard)
- Prod Tool Version: "league-prod-toolkit-core@1.9.1 start"
- Observer Tool Version: 6.12.0 (And previous version)

**Additional context**
If there is a fix pls tell me. I want to show the cool scoreboard again and have the Live Event popups like dragons etc. :)
Hoping to find someone that knows if this is my side and what I can do, or if its not my side.

**Additional Question:**
Also is there a way to pull the Team Pictures as individual Browser sources (and have them swap when I press swap?), I only seem to see them in the In game View, I'd like to use them for a break screen (with their score maybe?)

**Comment by sdomi4** [comment]
Thank you for the detailed report – unfortunately, LiveEvents has been removed from the game by Riot. The scoreboard is no longer functional due to the introduction of Vanguard.

Having the team pictures and such available is an open enhancement (https://github.com/RCVolus/league-prod-toolkit/issues/162), but probably not happening any time soon if at all, keep an eye out for announcements regarding the future of the toolkit.
