### ISSUE TITLE
Open Settings not working

### ISSUE THREAD

**Issue by derianchow** [RCVolus/league-observer-tool#2]
Every time I click Open Settings to setup the tool, no window opens up. Clicking connect gives me Connect ECONNREFUSED 127.0.0.1:3003.

**Comment by sdomi4** [comment]
In theory, your default editor for .json files should open, you might be able to fix this by setting one manually.
Otherwise, you can directly navigate to the file located in AppData at `C:\Users\[username]\AppData\Roaming\league-observer-tool` and edit config.json there as described in the readme.

The ECONNREFUSED indicates the toolkit is not running (or blocked by a firewall if running remotely).
